# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'textvideo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'VideoCompressor', :git => 'https://github.com/QiSDK/iOS_VideoCompressSDK.git', :tag => '1.0.5'
  pod 'SVProgressHUD'


  target 'textvideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'textvideoUITests' do
    # Pods for testing
  end

end
